// Code generated by go-swagger; DO NOT EDIT.

package customer_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// CreateCustomerGroupReader is a Reader for the CreateCustomerGroup structure.
type CreateCustomerGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCustomerGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCustomerGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCustomerGroupOK creates a CreateCustomerGroupOK with default headers values
func NewCreateCustomerGroupOK() *CreateCustomerGroupOK {
	return &CreateCustomerGroupOK{}
}

/*CreateCustomerGroupOK handles this case with default header values.

Success
*/
type CreateCustomerGroupOK struct {
	Payload *models.CreateCustomerGroupResponse
}

func (o *CreateCustomerGroupOK) Error() string {
	return fmt.Sprintf("[POST /v2/customers/groups][%d] createCustomerGroupOK  %+v", 200, o.Payload)
}

func (o *CreateCustomerGroupOK) GetPayload() *models.CreateCustomerGroupResponse {
	return o.Payload
}

func (o *CreateCustomerGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateCustomerGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
