// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddGroupToCustomerParams creates a new AddGroupToCustomerParams object
// with the default values initialized.
func NewAddGroupToCustomerParams() *AddGroupToCustomerParams {
	var ()
	return &AddGroupToCustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddGroupToCustomerParamsWithTimeout creates a new AddGroupToCustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddGroupToCustomerParamsWithTimeout(timeout time.Duration) *AddGroupToCustomerParams {
	var ()
	return &AddGroupToCustomerParams{

		timeout: timeout,
	}
}

// NewAddGroupToCustomerParamsWithContext creates a new AddGroupToCustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddGroupToCustomerParamsWithContext(ctx context.Context) *AddGroupToCustomerParams {
	var ()
	return &AddGroupToCustomerParams{

		Context: ctx,
	}
}

// NewAddGroupToCustomerParamsWithHTTPClient creates a new AddGroupToCustomerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddGroupToCustomerParamsWithHTTPClient(client *http.Client) *AddGroupToCustomerParams {
	var ()
	return &AddGroupToCustomerParams{
		HTTPClient: client,
	}
}

/*AddGroupToCustomerParams contains all the parameters to send to the API endpoint
for the add group to customer operation typically these are written to a http.Request
*/
type AddGroupToCustomerParams struct {

	/*CustomerID
	  The ID of the customer to add to a group.

	*/
	CustomerID string
	/*GroupID
	  The ID of the customer group to add the customer to.

	*/
	GroupID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add group to customer params
func (o *AddGroupToCustomerParams) WithTimeout(timeout time.Duration) *AddGroupToCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add group to customer params
func (o *AddGroupToCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add group to customer params
func (o *AddGroupToCustomerParams) WithContext(ctx context.Context) *AddGroupToCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add group to customer params
func (o *AddGroupToCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add group to customer params
func (o *AddGroupToCustomerParams) WithHTTPClient(client *http.Client) *AddGroupToCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add group to customer params
func (o *AddGroupToCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerID adds the customerID to the add group to customer params
func (o *AddGroupToCustomerParams) WithCustomerID(customerID string) *AddGroupToCustomerParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the add group to customer params
func (o *AddGroupToCustomerParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WithGroupID adds the groupID to the add group to customer params
func (o *AddGroupToCustomerParams) WithGroupID(groupID string) *AddGroupToCustomerParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the add group to customer params
func (o *AddGroupToCustomerParams) SetGroupID(groupID string) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *AddGroupToCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param customer_id
	if err := r.SetPathParam("customer_id", o.CustomerID); err != nil {
		return err
	}

	// path param group_id
	if err := r.SetPathParam("group_id", o.GroupID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
