// Code generated by go-swagger; DO NOT EDIT.

package customers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCustomerCardParams creates a new DeleteCustomerCardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCustomerCardParams() *DeleteCustomerCardParams {
	return &DeleteCustomerCardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCustomerCardParamsWithTimeout creates a new DeleteCustomerCardParams object
// with the ability to set a timeout on a request.
func NewDeleteCustomerCardParamsWithTimeout(timeout time.Duration) *DeleteCustomerCardParams {
	return &DeleteCustomerCardParams{
		timeout: timeout,
	}
}

// NewDeleteCustomerCardParamsWithContext creates a new DeleteCustomerCardParams object
// with the ability to set a context for a request.
func NewDeleteCustomerCardParamsWithContext(ctx context.Context) *DeleteCustomerCardParams {
	return &DeleteCustomerCardParams{
		Context: ctx,
	}
}

// NewDeleteCustomerCardParamsWithHTTPClient creates a new DeleteCustomerCardParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCustomerCardParamsWithHTTPClient(client *http.Client) *DeleteCustomerCardParams {
	return &DeleteCustomerCardParams{
		HTTPClient: client,
	}
}

/* DeleteCustomerCardParams contains all the parameters to send to the API endpoint
   for the delete customer card operation.

   Typically these are written to a http.Request.
*/
type DeleteCustomerCardParams struct {

	/* CardID.

	   The ID of the card on file to delete.
	*/
	CardID string

	/* CustomerID.

	   The ID of the customer that the card on file belongs to.
	*/
	CustomerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete customer card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCustomerCardParams) WithDefaults() *DeleteCustomerCardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete customer card params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCustomerCardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete customer card params
func (o *DeleteCustomerCardParams) WithTimeout(timeout time.Duration) *DeleteCustomerCardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete customer card params
func (o *DeleteCustomerCardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete customer card params
func (o *DeleteCustomerCardParams) WithContext(ctx context.Context) *DeleteCustomerCardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete customer card params
func (o *DeleteCustomerCardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete customer card params
func (o *DeleteCustomerCardParams) WithHTTPClient(client *http.Client) *DeleteCustomerCardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete customer card params
func (o *DeleteCustomerCardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCardID adds the cardID to the delete customer card params
func (o *DeleteCustomerCardParams) WithCardID(cardID string) *DeleteCustomerCardParams {
	o.SetCardID(cardID)
	return o
}

// SetCardID adds the cardId to the delete customer card params
func (o *DeleteCustomerCardParams) SetCardID(cardID string) {
	o.CardID = cardID
}

// WithCustomerID adds the customerID to the delete customer card params
func (o *DeleteCustomerCardParams) WithCustomerID(customerID string) *DeleteCustomerCardParams {
	o.SetCustomerID(customerID)
	return o
}

// SetCustomerID adds the customerId to the delete customer card params
func (o *DeleteCustomerCardParams) SetCustomerID(customerID string) {
	o.CustomerID = customerID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCustomerCardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param card_id
	if err := r.SetPathParam("card_id", o.CardID); err != nil {
		return err
	}

	// path param customer_id
	if err := r.SetPathParam("customer_id", o.CustomerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
