// Code generated by go-swagger; DO NOT EDIT.

package bookings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewUpdateBookingParams creates a new UpdateBookingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateBookingParams() *UpdateBookingParams {
	return &UpdateBookingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBookingParamsWithTimeout creates a new UpdateBookingParams object
// with the ability to set a timeout on a request.
func NewUpdateBookingParamsWithTimeout(timeout time.Duration) *UpdateBookingParams {
	return &UpdateBookingParams{
		timeout: timeout,
	}
}

// NewUpdateBookingParamsWithContext creates a new UpdateBookingParams object
// with the ability to set a context for a request.
func NewUpdateBookingParamsWithContext(ctx context.Context) *UpdateBookingParams {
	return &UpdateBookingParams{
		Context: ctx,
	}
}

// NewUpdateBookingParamsWithHTTPClient creates a new UpdateBookingParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateBookingParamsWithHTTPClient(client *http.Client) *UpdateBookingParams {
	return &UpdateBookingParams{
		HTTPClient: client,
	}
}

/* UpdateBookingParams contains all the parameters to send to the API endpoint
   for the update booking operation.

   Typically these are written to a http.Request.
*/
type UpdateBookingParams struct {

	/* Body.

	     An object containing the fields to POST for the request.

	See the corresponding object definition for field details.
	*/
	Body *models.UpdateBookingRequest

	/* BookingID.

	   The ID of the `Booking` object representing the to-be-updated booking.
	*/
	BookingID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update booking params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBookingParams) WithDefaults() *UpdateBookingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update booking params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBookingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update booking params
func (o *UpdateBookingParams) WithTimeout(timeout time.Duration) *UpdateBookingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update booking params
func (o *UpdateBookingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update booking params
func (o *UpdateBookingParams) WithContext(ctx context.Context) *UpdateBookingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update booking params
func (o *UpdateBookingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update booking params
func (o *UpdateBookingParams) WithHTTPClient(client *http.Client) *UpdateBookingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update booking params
func (o *UpdateBookingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update booking params
func (o *UpdateBookingParams) WithBody(body *models.UpdateBookingRequest) *UpdateBookingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update booking params
func (o *UpdateBookingParams) SetBody(body *models.UpdateBookingRequest) {
	o.Body = body
}

// WithBookingID adds the bookingID to the update booking params
func (o *UpdateBookingParams) WithBookingID(bookingID string) *UpdateBookingParams {
	o.SetBookingID(bookingID)
	return o
}

// SetBookingID adds the bookingId to the update booking params
func (o *UpdateBookingParams) SetBookingID(bookingID string) {
	o.BookingID = bookingID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBookingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param booking_id
	if err := r.SetPathParam("booking_id", o.BookingID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
