// Code generated by go-swagger; DO NOT EDIT.

package v1_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// ListOrdersReader is a Reader for the ListOrders structure.
type ListOrdersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOrdersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOrdersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListOrdersOK creates a ListOrdersOK with default headers values
func NewListOrdersOK() *ListOrdersOK {
	return &ListOrdersOK{}
}

/*ListOrdersOK handles this case with default header values.

Success
*/
type ListOrdersOK struct {
	Payload []*models.V1Order
}

func (o *ListOrdersOK) Error() string {
	return fmt.Sprintf("[GET /v1/{location_id}/orders][%d] listOrdersOK  %+v", 200, o.Payload)
}

func (o *ListOrdersOK) GetPayload() []*models.V1Order {
	return o.Payload
}

func (o *ListOrdersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
