// Code generated by go-swagger; DO NOT EDIT.

package v1_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// ListSettlementsReader is a Reader for the ListSettlements structure.
type ListSettlementsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSettlementsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSettlementsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSettlementsOK creates a ListSettlementsOK with default headers values
func NewListSettlementsOK() *ListSettlementsOK {
	return &ListSettlementsOK{}
}

/*ListSettlementsOK handles this case with default header values.

Success
*/
type ListSettlementsOK struct {
	Payload []*models.V1Settlement
}

func (o *ListSettlementsOK) Error() string {
	return fmt.Sprintf("[GET /v1/{location_id}/settlements][%d] listSettlementsOK  %+v", 200, o.Payload)
}

func (o *ListSettlementsOK) GetPayload() []*models.V1Settlement {
	return o.Payload
}

func (o *ListSettlementsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
