// Code generated by go-swagger; DO NOT EDIT.

package terminal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCancelTerminalRefundParams creates a new CancelTerminalRefundParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCancelTerminalRefundParams() *CancelTerminalRefundParams {
	return &CancelTerminalRefundParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCancelTerminalRefundParamsWithTimeout creates a new CancelTerminalRefundParams object
// with the ability to set a timeout on a request.
func NewCancelTerminalRefundParamsWithTimeout(timeout time.Duration) *CancelTerminalRefundParams {
	return &CancelTerminalRefundParams{
		timeout: timeout,
	}
}

// NewCancelTerminalRefundParamsWithContext creates a new CancelTerminalRefundParams object
// with the ability to set a context for a request.
func NewCancelTerminalRefundParamsWithContext(ctx context.Context) *CancelTerminalRefundParams {
	return &CancelTerminalRefundParams{
		Context: ctx,
	}
}

// NewCancelTerminalRefundParamsWithHTTPClient creates a new CancelTerminalRefundParams object
// with the ability to set a custom HTTPClient for a request.
func NewCancelTerminalRefundParamsWithHTTPClient(client *http.Client) *CancelTerminalRefundParams {
	return &CancelTerminalRefundParams{
		HTTPClient: client,
	}
}

/* CancelTerminalRefundParams contains all the parameters to send to the API endpoint
   for the cancel terminal refund operation.

   Typically these are written to a http.Request.
*/
type CancelTerminalRefundParams struct {

	/* TerminalRefundID.

	   Unique ID for the desired `TerminalRefund`
	*/
	TerminalRefundID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cancel terminal refund params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelTerminalRefundParams) WithDefaults() *CancelTerminalRefundParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cancel terminal refund params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelTerminalRefundParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cancel terminal refund params
func (o *CancelTerminalRefundParams) WithTimeout(timeout time.Duration) *CancelTerminalRefundParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel terminal refund params
func (o *CancelTerminalRefundParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel terminal refund params
func (o *CancelTerminalRefundParams) WithContext(ctx context.Context) *CancelTerminalRefundParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel terminal refund params
func (o *CancelTerminalRefundParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel terminal refund params
func (o *CancelTerminalRefundParams) WithHTTPClient(client *http.Client) *CancelTerminalRefundParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel terminal refund params
func (o *CancelTerminalRefundParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTerminalRefundID adds the terminalRefundID to the cancel terminal refund params
func (o *CancelTerminalRefundParams) WithTerminalRefundID(terminalRefundID string) *CancelTerminalRefundParams {
	o.SetTerminalRefundID(terminalRefundID)
	return o
}

// SetTerminalRefundID adds the terminalRefundId to the cancel terminal refund params
func (o *CancelTerminalRefundParams) SetTerminalRefundID(terminalRefundID string) {
	o.TerminalRefundID = terminalRefundID
}

// WriteToRequest writes these params to a swagger request
func (o *CancelTerminalRefundParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param terminal_refund_id
	if err := r.SetPathParam("terminal_refund_id", o.TerminalRefundID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
