// Code generated by go-swagger; DO NOT EDIT.

package loyalty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewAccumulateLoyaltyPointsParams creates a new AccumulateLoyaltyPointsParams object
// with the default values initialized.
func NewAccumulateLoyaltyPointsParams() *AccumulateLoyaltyPointsParams {
	var ()
	return &AccumulateLoyaltyPointsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAccumulateLoyaltyPointsParamsWithTimeout creates a new AccumulateLoyaltyPointsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAccumulateLoyaltyPointsParamsWithTimeout(timeout time.Duration) *AccumulateLoyaltyPointsParams {
	var ()
	return &AccumulateLoyaltyPointsParams{

		timeout: timeout,
	}
}

// NewAccumulateLoyaltyPointsParamsWithContext creates a new AccumulateLoyaltyPointsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAccumulateLoyaltyPointsParamsWithContext(ctx context.Context) *AccumulateLoyaltyPointsParams {
	var ()
	return &AccumulateLoyaltyPointsParams{

		Context: ctx,
	}
}

// NewAccumulateLoyaltyPointsParamsWithHTTPClient creates a new AccumulateLoyaltyPointsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAccumulateLoyaltyPointsParamsWithHTTPClient(client *http.Client) *AccumulateLoyaltyPointsParams {
	var ()
	return &AccumulateLoyaltyPointsParams{
		HTTPClient: client,
	}
}

/*AccumulateLoyaltyPointsParams contains all the parameters to send to the API endpoint
for the accumulate loyalty points operation typically these are written to a http.Request
*/
type AccumulateLoyaltyPointsParams struct {

	/*AccountID
	  The `loyalty account` ID to which to add the points.

	*/
	AccountID string
	/*Body
	  An object containing the fields to POST for the request.

	See the corresponding object definition for field details.

	*/
	Body *models.AccumulateLoyaltyPointsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) WithTimeout(timeout time.Duration) *AccumulateLoyaltyPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) WithContext(ctx context.Context) *AccumulateLoyaltyPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) WithHTTPClient(client *http.Client) *AccumulateLoyaltyPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) WithAccountID(accountID string) *AccumulateLoyaltyPointsParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) WithBody(body *models.AccumulateLoyaltyPointsRequest) *AccumulateLoyaltyPointsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the accumulate loyalty points params
func (o *AccumulateLoyaltyPointsParams) SetBody(body *models.AccumulateLoyaltyPointsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AccumulateLoyaltyPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
