// Code generated by go-swagger; DO NOT EDIT.

package loyalty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewCreateLoyaltyRewardParams creates a new CreateLoyaltyRewardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateLoyaltyRewardParams() *CreateLoyaltyRewardParams {
	return &CreateLoyaltyRewardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateLoyaltyRewardParamsWithTimeout creates a new CreateLoyaltyRewardParams object
// with the ability to set a timeout on a request.
func NewCreateLoyaltyRewardParamsWithTimeout(timeout time.Duration) *CreateLoyaltyRewardParams {
	return &CreateLoyaltyRewardParams{
		timeout: timeout,
	}
}

// NewCreateLoyaltyRewardParamsWithContext creates a new CreateLoyaltyRewardParams object
// with the ability to set a context for a request.
func NewCreateLoyaltyRewardParamsWithContext(ctx context.Context) *CreateLoyaltyRewardParams {
	return &CreateLoyaltyRewardParams{
		Context: ctx,
	}
}

// NewCreateLoyaltyRewardParamsWithHTTPClient creates a new CreateLoyaltyRewardParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateLoyaltyRewardParamsWithHTTPClient(client *http.Client) *CreateLoyaltyRewardParams {
	return &CreateLoyaltyRewardParams{
		HTTPClient: client,
	}
}

/* CreateLoyaltyRewardParams contains all the parameters to send to the API endpoint
   for the create loyalty reward operation.

   Typically these are written to a http.Request.
*/
type CreateLoyaltyRewardParams struct {

	/* Body.

	     An object containing the fields to POST for the request.

	See the corresponding object definition for field details.
	*/
	Body *models.CreateLoyaltyRewardRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create loyalty reward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateLoyaltyRewardParams) WithDefaults() *CreateLoyaltyRewardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create loyalty reward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateLoyaltyRewardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) WithTimeout(timeout time.Duration) *CreateLoyaltyRewardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) WithContext(ctx context.Context) *CreateLoyaltyRewardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) WithHTTPClient(client *http.Client) *CreateLoyaltyRewardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) WithBody(body *models.CreateLoyaltyRewardRequest) *CreateLoyaltyRewardParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create loyalty reward params
func (o *CreateLoyaltyRewardParams) SetBody(body *models.CreateLoyaltyRewardRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateLoyaltyRewardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
