// Code generated by go-swagger; DO NOT EDIT.

package loyalty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewRedeemLoyaltyRewardParams creates a new RedeemLoyaltyRewardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRedeemLoyaltyRewardParams() *RedeemLoyaltyRewardParams {
	return &RedeemLoyaltyRewardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRedeemLoyaltyRewardParamsWithTimeout creates a new RedeemLoyaltyRewardParams object
// with the ability to set a timeout on a request.
func NewRedeemLoyaltyRewardParamsWithTimeout(timeout time.Duration) *RedeemLoyaltyRewardParams {
	return &RedeemLoyaltyRewardParams{
		timeout: timeout,
	}
}

// NewRedeemLoyaltyRewardParamsWithContext creates a new RedeemLoyaltyRewardParams object
// with the ability to set a context for a request.
func NewRedeemLoyaltyRewardParamsWithContext(ctx context.Context) *RedeemLoyaltyRewardParams {
	return &RedeemLoyaltyRewardParams{
		Context: ctx,
	}
}

// NewRedeemLoyaltyRewardParamsWithHTTPClient creates a new RedeemLoyaltyRewardParams object
// with the ability to set a custom HTTPClient for a request.
func NewRedeemLoyaltyRewardParamsWithHTTPClient(client *http.Client) *RedeemLoyaltyRewardParams {
	return &RedeemLoyaltyRewardParams{
		HTTPClient: client,
	}
}

/* RedeemLoyaltyRewardParams contains all the parameters to send to the API endpoint
   for the redeem loyalty reward operation.

   Typically these are written to a http.Request.
*/
type RedeemLoyaltyRewardParams struct {

	/* Body.

	     An object containing the fields to POST for the request.

	See the corresponding object definition for field details.
	*/
	Body *models.RedeemLoyaltyRewardRequest

	/* RewardID.

	   The ID of the `loyalty reward` to redeem.
	*/
	RewardID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the redeem loyalty reward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RedeemLoyaltyRewardParams) WithDefaults() *RedeemLoyaltyRewardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the redeem loyalty reward params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RedeemLoyaltyRewardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) WithTimeout(timeout time.Duration) *RedeemLoyaltyRewardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) WithContext(ctx context.Context) *RedeemLoyaltyRewardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) WithHTTPClient(client *http.Client) *RedeemLoyaltyRewardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) WithBody(body *models.RedeemLoyaltyRewardRequest) *RedeemLoyaltyRewardParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) SetBody(body *models.RedeemLoyaltyRewardRequest) {
	o.Body = body
}

// WithRewardID adds the rewardID to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) WithRewardID(rewardID string) *RedeemLoyaltyRewardParams {
	o.SetRewardID(rewardID)
	return o
}

// SetRewardID adds the rewardId to the redeem loyalty reward params
func (o *RedeemLoyaltyRewardParams) SetRewardID(rewardID string) {
	o.RewardID = rewardID
}

// WriteToRequest writes these params to a swagger request
func (o *RedeemLoyaltyRewardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param reward_id
	if err := r.SetPathParam("reward_id", o.RewardID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
