// Code generated by go-swagger; DO NOT EDIT.

package loyalty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// RedeemLoyaltyRewardReader is a Reader for the RedeemLoyaltyReward structure.
type RedeemLoyaltyRewardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RedeemLoyaltyRewardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRedeemLoyaltyRewardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRedeemLoyaltyRewardOK creates a RedeemLoyaltyRewardOK with default headers values
func NewRedeemLoyaltyRewardOK() *RedeemLoyaltyRewardOK {
	return &RedeemLoyaltyRewardOK{}
}

/*RedeemLoyaltyRewardOK handles this case with default header values.

Success
*/
type RedeemLoyaltyRewardOK struct {
	Payload *models.RedeemLoyaltyRewardResponse
}

func (o *RedeemLoyaltyRewardOK) Error() string {
	return fmt.Sprintf("[POST /v2/loyalty/rewards/{reward_id}/redeem][%d] redeemLoyaltyRewardOK  %+v", 200, o.Payload)
}

func (o *RedeemLoyaltyRewardOK) GetPayload() *models.RedeemLoyaltyRewardResponse {
	return o.Payload
}

func (o *RedeemLoyaltyRewardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RedeemLoyaltyRewardResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
