// Code generated by go-swagger; DO NOT EDIT.

package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewSearchCatalogObjectsParams creates a new SearchCatalogObjectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchCatalogObjectsParams() *SearchCatalogObjectsParams {
	return &SearchCatalogObjectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchCatalogObjectsParamsWithTimeout creates a new SearchCatalogObjectsParams object
// with the ability to set a timeout on a request.
func NewSearchCatalogObjectsParamsWithTimeout(timeout time.Duration) *SearchCatalogObjectsParams {
	return &SearchCatalogObjectsParams{
		timeout: timeout,
	}
}

// NewSearchCatalogObjectsParamsWithContext creates a new SearchCatalogObjectsParams object
// with the ability to set a context for a request.
func NewSearchCatalogObjectsParamsWithContext(ctx context.Context) *SearchCatalogObjectsParams {
	return &SearchCatalogObjectsParams{
		Context: ctx,
	}
}

// NewSearchCatalogObjectsParamsWithHTTPClient creates a new SearchCatalogObjectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchCatalogObjectsParamsWithHTTPClient(client *http.Client) *SearchCatalogObjectsParams {
	return &SearchCatalogObjectsParams{
		HTTPClient: client,
	}
}

/* SearchCatalogObjectsParams contains all the parameters to send to the API endpoint
   for the search catalog objects operation.

   Typically these are written to a http.Request.
*/
type SearchCatalogObjectsParams struct {

	/* Body.

	     An object containing the fields to POST for the request.

	See the corresponding object definition for field details.
	*/
	Body *models.SearchCatalogObjectsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search catalog objects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCatalogObjectsParams) WithDefaults() *SearchCatalogObjectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search catalog objects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCatalogObjectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search catalog objects params
func (o *SearchCatalogObjectsParams) WithTimeout(timeout time.Duration) *SearchCatalogObjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search catalog objects params
func (o *SearchCatalogObjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search catalog objects params
func (o *SearchCatalogObjectsParams) WithContext(ctx context.Context) *SearchCatalogObjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search catalog objects params
func (o *SearchCatalogObjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search catalog objects params
func (o *SearchCatalogObjectsParams) WithHTTPClient(client *http.Client) *SearchCatalogObjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search catalog objects params
func (o *SearchCatalogObjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search catalog objects params
func (o *SearchCatalogObjectsParams) WithBody(body *models.SearchCatalogObjectsRequest) *SearchCatalogObjectsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search catalog objects params
func (o *SearchCatalogObjectsParams) SetBody(body *models.SearchCatalogObjectsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchCatalogObjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
