// Code generated by go-swagger; DO NOT EDIT.

package invoices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// NewCancelInvoiceParams creates a new CancelInvoiceParams object
// with the default values initialized.
func NewCancelInvoiceParams() *CancelInvoiceParams {
	var ()
	return &CancelInvoiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelInvoiceParamsWithTimeout creates a new CancelInvoiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelInvoiceParamsWithTimeout(timeout time.Duration) *CancelInvoiceParams {
	var ()
	return &CancelInvoiceParams{

		timeout: timeout,
	}
}

// NewCancelInvoiceParamsWithContext creates a new CancelInvoiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelInvoiceParamsWithContext(ctx context.Context) *CancelInvoiceParams {
	var ()
	return &CancelInvoiceParams{

		Context: ctx,
	}
}

// NewCancelInvoiceParamsWithHTTPClient creates a new CancelInvoiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelInvoiceParamsWithHTTPClient(client *http.Client) *CancelInvoiceParams {
	var ()
	return &CancelInvoiceParams{
		HTTPClient: client,
	}
}

/*CancelInvoiceParams contains all the parameters to send to the API endpoint
for the cancel invoice operation typically these are written to a http.Request
*/
type CancelInvoiceParams struct {

	/*Body
	  An object containing the fields to POST for the request.

	See the corresponding object definition for field details.

	*/
	Body *models.CancelInvoiceRequest
	/*InvoiceID
	  The ID of the `invoice` to cancel.

	*/
	InvoiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel invoice params
func (o *CancelInvoiceParams) WithTimeout(timeout time.Duration) *CancelInvoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel invoice params
func (o *CancelInvoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel invoice params
func (o *CancelInvoiceParams) WithContext(ctx context.Context) *CancelInvoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel invoice params
func (o *CancelInvoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel invoice params
func (o *CancelInvoiceParams) WithHTTPClient(client *http.Client) *CancelInvoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel invoice params
func (o *CancelInvoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the cancel invoice params
func (o *CancelInvoiceParams) WithBody(body *models.CancelInvoiceRequest) *CancelInvoiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the cancel invoice params
func (o *CancelInvoiceParams) SetBody(body *models.CancelInvoiceRequest) {
	o.Body = body
}

// WithInvoiceID adds the invoiceID to the cancel invoice params
func (o *CancelInvoiceParams) WithInvoiceID(invoiceID string) *CancelInvoiceParams {
	o.SetInvoiceID(invoiceID)
	return o
}

// SetInvoiceID adds the invoiceId to the cancel invoice params
func (o *CancelInvoiceParams) SetInvoiceID(invoiceID string) {
	o.InvoiceID = invoiceID
}

// WriteToRequest writes these params to a swagger request
func (o *CancelInvoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param invoice_id
	if err := r.SetPathParam("invoice_id", o.InvoiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
