// Code generated by go-swagger; DO NOT EDIT.

package cash_drawers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// ListCashDrawerShiftEventsReader is a Reader for the ListCashDrawerShiftEvents structure.
type ListCashDrawerShiftEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCashDrawerShiftEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListCashDrawerShiftEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListCashDrawerShiftEventsOK creates a ListCashDrawerShiftEventsOK with default headers values
func NewListCashDrawerShiftEventsOK() *ListCashDrawerShiftEventsOK {
	return &ListCashDrawerShiftEventsOK{}
}

/*ListCashDrawerShiftEventsOK handles this case with default header values.

Success
*/
type ListCashDrawerShiftEventsOK struct {
	Payload *models.ListCashDrawerShiftEventsResponse
}

func (o *ListCashDrawerShiftEventsOK) Error() string {
	return fmt.Sprintf("[GET /v2/cash-drawers/shifts/{shift_id}/events][%d] listCashDrawerShiftEventsOK  %+v", 200, o.Payload)
}

func (o *ListCashDrawerShiftEventsOK) GetPayload() *models.ListCashDrawerShiftEventsResponse {
	return o.Payload
}

func (o *ListCashDrawerShiftEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListCashDrawerShiftEventsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
