// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveTransactionParams creates a new RetrieveTransactionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveTransactionParams() *RetrieveTransactionParams {
	return &RetrieveTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveTransactionParamsWithTimeout creates a new RetrieveTransactionParams object
// with the ability to set a timeout on a request.
func NewRetrieveTransactionParamsWithTimeout(timeout time.Duration) *RetrieveTransactionParams {
	return &RetrieveTransactionParams{
		timeout: timeout,
	}
}

// NewRetrieveTransactionParamsWithContext creates a new RetrieveTransactionParams object
// with the ability to set a context for a request.
func NewRetrieveTransactionParamsWithContext(ctx context.Context) *RetrieveTransactionParams {
	return &RetrieveTransactionParams{
		Context: ctx,
	}
}

// NewRetrieveTransactionParamsWithHTTPClient creates a new RetrieveTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveTransactionParamsWithHTTPClient(client *http.Client) *RetrieveTransactionParams {
	return &RetrieveTransactionParams{
		HTTPClient: client,
	}
}

/* RetrieveTransactionParams contains all the parameters to send to the API endpoint
   for the retrieve transaction operation.

   Typically these are written to a http.Request.
*/
type RetrieveTransactionParams struct {

	/* LocationID.

	   The ID of the transaction's associated location.
	*/
	LocationID string

	/* TransactionID.

	   The ID of the transaction to retrieve.
	*/
	TransactionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveTransactionParams) WithDefaults() *RetrieveTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve transaction params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the retrieve transaction params
func (o *RetrieveTransactionParams) WithTimeout(timeout time.Duration) *RetrieveTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve transaction params
func (o *RetrieveTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve transaction params
func (o *RetrieveTransactionParams) WithContext(ctx context.Context) *RetrieveTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve transaction params
func (o *RetrieveTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve transaction params
func (o *RetrieveTransactionParams) WithHTTPClient(client *http.Client) *RetrieveTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve transaction params
func (o *RetrieveTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLocationID adds the locationID to the retrieve transaction params
func (o *RetrieveTransactionParams) WithLocationID(locationID string) *RetrieveTransactionParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the retrieve transaction params
func (o *RetrieveTransactionParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithTransactionID adds the transactionID to the retrieve transaction params
func (o *RetrieveTransactionParams) WithTransactionID(transactionID string) *RetrieveTransactionParams {
	o.SetTransactionID(transactionID)
	return o
}

// SetTransactionID adds the transactionId to the retrieve transaction params
func (o *RetrieveTransactionParams) SetTransactionID(transactionID string) {
	o.TransactionID = transactionID
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param location_id
	if err := r.SetPathParam("location_id", o.LocationID); err != nil {
		return err
	}

	// path param transaction_id
	if err := r.SetPathParam("transaction_id", o.TransactionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
