// Code generated by go-swagger; DO NOT EDIT.

package merchants

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// RetrieveMerchantReader is a Reader for the RetrieveMerchant structure.
type RetrieveMerchantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetrieveMerchantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRetrieveMerchantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRetrieveMerchantOK creates a RetrieveMerchantOK with default headers values
func NewRetrieveMerchantOK() *RetrieveMerchantOK {
	return &RetrieveMerchantOK{}
}

/* RetrieveMerchantOK describes a response with status code 200, with default header values.

Success
*/
type RetrieveMerchantOK struct {
	Payload *models.RetrieveMerchantResponse
}

func (o *RetrieveMerchantOK) Error() string {
	return fmt.Sprintf("[GET /v2/merchants/{merchant_id}][%d] retrieveMerchantOK  %+v", 200, o.Payload)
}
func (o *RetrieveMerchantOK) GetPayload() *models.RetrieveMerchantResponse {
	return o.Payload
}

func (o *RetrieveMerchantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RetrieveMerchantResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
