// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCompletePaymentParams creates a new CompletePaymentParams object
// with the default values initialized.
func NewCompletePaymentParams() *CompletePaymentParams {
	var ()
	return &CompletePaymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCompletePaymentParamsWithTimeout creates a new CompletePaymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCompletePaymentParamsWithTimeout(timeout time.Duration) *CompletePaymentParams {
	var ()
	return &CompletePaymentParams{

		timeout: timeout,
	}
}

// NewCompletePaymentParamsWithContext creates a new CompletePaymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewCompletePaymentParamsWithContext(ctx context.Context) *CompletePaymentParams {
	var ()
	return &CompletePaymentParams{

		Context: ctx,
	}
}

// NewCompletePaymentParamsWithHTTPClient creates a new CompletePaymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCompletePaymentParamsWithHTTPClient(client *http.Client) *CompletePaymentParams {
	var ()
	return &CompletePaymentParams{
		HTTPClient: client,
	}
}

/*CompletePaymentParams contains all the parameters to send to the API endpoint
for the complete payment operation typically these are written to a http.Request
*/
type CompletePaymentParams struct {

	/*PaymentID
	  Unique ID identifying the payment to be completed.

	*/
	PaymentID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the complete payment params
func (o *CompletePaymentParams) WithTimeout(timeout time.Duration) *CompletePaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the complete payment params
func (o *CompletePaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the complete payment params
func (o *CompletePaymentParams) WithContext(ctx context.Context) *CompletePaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the complete payment params
func (o *CompletePaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the complete payment params
func (o *CompletePaymentParams) WithHTTPClient(client *http.Client) *CompletePaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the complete payment params
func (o *CompletePaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaymentID adds the paymentID to the complete payment params
func (o *CompletePaymentParams) WithPaymentID(paymentID string) *CompletePaymentParams {
	o.SetPaymentID(paymentID)
	return o
}

// SetPaymentID adds the paymentId to the complete payment params
func (o *CompletePaymentParams) SetPaymentID(paymentID string) {
	o.PaymentID = paymentID
}

// WriteToRequest writes these params to a swagger request
func (o *CompletePaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param payment_id
	if err := r.SetPathParam("payment_id", o.PaymentID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
