// Code generated by go-swagger; DO NOT EDIT.

package v1_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// CreateCategoryReader is a Reader for the CreateCategory structure.
type CreateCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCategoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCategoryOK creates a CreateCategoryOK with default headers values
func NewCreateCategoryOK() *CreateCategoryOK {
	return &CreateCategoryOK{}
}

/*CreateCategoryOK handles this case with default header values.

Success
*/
type CreateCategoryOK struct {
	Payload *models.V1Category
}

func (o *CreateCategoryOK) Error() string {
	return fmt.Sprintf("[POST /v1/{location_id}/categories][%d] createCategoryOK  %+v", 200, o.Payload)
}

func (o *CreateCategoryOK) GetPayload() *models.V1Category {
	return o.Payload
}

func (o *CreateCategoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1Category)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
