// Code generated by go-swagger; DO NOT EDIT.

package v1_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// DeletePageReader is a Reader for the DeletePage structure.
type DeletePageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePageOK creates a DeletePageOK with default headers values
func NewDeletePageOK() *DeletePageOK {
	return &DeletePageOK{}
}

/*DeletePageOK handles this case with default header values.

Success
*/
type DeletePageOK struct {
	Payload *models.V1Page
}

func (o *DeletePageOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/{location_id}/pages/{page_id}][%d] deletePageOK  %+v", 200, o.Payload)
}

func (o *DeletePageOK) GetPayload() *models.V1Page {
	return o.Payload
}

func (o *DeletePageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1Page)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
