// Code generated by go-swagger; DO NOT EDIT.

package v1_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// DeletePageCellReader is a Reader for the DeletePageCell structure.
type DeletePageCellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePageCellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePageCellOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePageCellOK creates a DeletePageCellOK with default headers values
func NewDeletePageCellOK() *DeletePageCellOK {
	return &DeletePageCellOK{}
}

/*DeletePageCellOK handles this case with default header values.

Success
*/
type DeletePageCellOK struct {
	Payload *models.V1Page
}

func (o *DeletePageCellOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/{location_id}/pages/{page_id}/cells][%d] deletePageCellOK  %+v", 200, o.Payload)
}

func (o *DeletePageCellOK) GetPayload() *models.V1Page {
	return o.Payload
}

func (o *DeletePageCellOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1Page)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
