// Code generated by go-swagger; DO NOT EDIT.

package v1_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// ListFeesReader is a Reader for the ListFees structure.
type ListFeesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListFeesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListFeesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListFeesOK creates a ListFeesOK with default headers values
func NewListFeesOK() *ListFeesOK {
	return &ListFeesOK{}
}

/*ListFeesOK handles this case with default header values.

Success
*/
type ListFeesOK struct {
	Payload []*models.V1Fee
}

func (o *ListFeesOK) Error() string {
	return fmt.Sprintf("[GET /v1/{location_id}/fees][%d] listFeesOK  %+v", 200, o.Payload)
}

func (o *ListFeesOK) GetPayload() []*models.V1Fee {
	return o.Payload
}

func (o *ListFeesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
