// Code generated by go-swagger; DO NOT EDIT.

package v1_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// RetrieveItemReader is a Reader for the RetrieveItem structure.
type RetrieveItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetrieveItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRetrieveItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRetrieveItemOK creates a RetrieveItemOK with default headers values
func NewRetrieveItemOK() *RetrieveItemOK {
	return &RetrieveItemOK{}
}

/*RetrieveItemOK handles this case with default header values.

Success
*/
type RetrieveItemOK struct {
	Payload *models.V1Item
}

func (o *RetrieveItemOK) Error() string {
	return fmt.Sprintf("[GET /v1/{location_id}/items/{item_id}][%d] retrieveItemOK  %+v", 200, o.Payload)
}

func (o *RetrieveItemOK) GetPayload() *models.V1Item {
	return o.Payload
}

func (o *RetrieveItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
