// Code generated by go-swagger; DO NOT EDIT.

package employees

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveEmployeeParams creates a new RetrieveEmployeeParams object
// with the default values initialized.
func NewRetrieveEmployeeParams() *RetrieveEmployeeParams {
	var ()
	return &RetrieveEmployeeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveEmployeeParamsWithTimeout creates a new RetrieveEmployeeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRetrieveEmployeeParamsWithTimeout(timeout time.Duration) *RetrieveEmployeeParams {
	var ()
	return &RetrieveEmployeeParams{

		timeout: timeout,
	}
}

// NewRetrieveEmployeeParamsWithContext creates a new RetrieveEmployeeParams object
// with the default values initialized, and the ability to set a context for a request
func NewRetrieveEmployeeParamsWithContext(ctx context.Context) *RetrieveEmployeeParams {
	var ()
	return &RetrieveEmployeeParams{

		Context: ctx,
	}
}

// NewRetrieveEmployeeParamsWithHTTPClient creates a new RetrieveEmployeeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRetrieveEmployeeParamsWithHTTPClient(client *http.Client) *RetrieveEmployeeParams {
	var ()
	return &RetrieveEmployeeParams{
		HTTPClient: client,
	}
}

/*RetrieveEmployeeParams contains all the parameters to send to the API endpoint
for the retrieve employee operation typically these are written to a http.Request
*/
type RetrieveEmployeeParams struct {

	/*ID
	  UUID for the employee that was requested.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the retrieve employee params
func (o *RetrieveEmployeeParams) WithTimeout(timeout time.Duration) *RetrieveEmployeeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve employee params
func (o *RetrieveEmployeeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve employee params
func (o *RetrieveEmployeeParams) WithContext(ctx context.Context) *RetrieveEmployeeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve employee params
func (o *RetrieveEmployeeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve employee params
func (o *RetrieveEmployeeParams) WithHTTPClient(client *http.Client) *RetrieveEmployeeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve employee params
func (o *RetrieveEmployeeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the retrieve employee params
func (o *RetrieveEmployeeParams) WithID(id string) *RetrieveEmployeeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the retrieve employee params
func (o *RetrieveEmployeeParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveEmployeeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
