// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CancelTerminalCheckoutResponse cancel terminal checkout response
// Example: {"checkout":{"amount_money":{"amount":123,"currency":"USD"},"app_id":"APP_ID","cancel_reason":"SELLER_CANCELED","created_at":"2020-03-16T15:31:19.934Z","deadline_duration":"PT10M","device_options":{"device_id":"dbb5d83a-7838-11ea-bc55-0242ac130003","skip_receipt_screen":true,"tip_settings":{"allow_tipping":true}},"id":"S1yDlPQx7slqO","reference_id":"id36815","status":"CANCELED","updated_at":"2020-03-16T15:31:45.787Z"}}
//
// swagger:model CancelTerminalCheckoutResponse
type CancelTerminalCheckoutResponse struct {

	// The canceled `TerminalCheckout`
	Checkout *TerminalCheckout `json:"checkout,omitempty"`

	// Information on errors encountered during the request.
	Errors []*Error `json:"errors"`
}

// Validate validates this cancel terminal checkout response
func (m *CancelTerminalCheckoutResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCheckout(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CancelTerminalCheckoutResponse) validateCheckout(formats strfmt.Registry) error {
	if swag.IsZero(m.Checkout) { // not required
		return nil
	}

	if m.Checkout != nil {
		if err := m.Checkout.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("checkout")
			}
			return err
		}
	}

	return nil
}

func (m *CancelTerminalCheckoutResponse) validateErrors(formats strfmt.Registry) error {
	if swag.IsZero(m.Errors) { // not required
		return nil
	}

	for i := 0; i < len(m.Errors); i++ {
		if swag.IsZero(m.Errors[i]) { // not required
			continue
		}

		if m.Errors[i] != nil {
			if err := m.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this cancel terminal checkout response based on the context it is used
func (m *CancelTerminalCheckoutResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCheckout(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateErrors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CancelTerminalCheckoutResponse) contextValidateCheckout(ctx context.Context, formats strfmt.Registry) error {

	if m.Checkout != nil {
		if err := m.Checkout.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("checkout")
			}
			return err
		}
	}

	return nil
}

func (m *CancelTerminalCheckoutResponse) contextValidateErrors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Errors); i++ {

		if m.Errors[i] != nil {
			if err := m.Errors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CancelTerminalCheckoutResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CancelTerminalCheckoutResponse) UnmarshalBinary(b []byte) error {
	var res CancelTerminalCheckoutResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
