// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetPaymentRefundResponse Defines the fields that are included in the response body of
// a request to the [GetRefund](#endpoint-refunds-getpaymentrefund) endpoint.
//
// Note: if there are errors processing the request, the refund field may not be
// present, or it may be present in a FAILED state.
//
// swagger:model GetPaymentRefundResponse
type GetPaymentRefundResponse struct {

	// Information on errors encountered during the request.
	Errors []*Error `json:"errors"`

	// The requested `PaymentRefund`.
	Refund *PaymentRefund `json:"refund,omitempty"`
}

// Validate validates this get payment refund response
func (m *GetPaymentRefundResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefund(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetPaymentRefundResponse) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.Errors) { // not required
		return nil
	}

	for i := 0; i < len(m.Errors); i++ {
		if swag.IsZero(m.Errors[i]) { // not required
			continue
		}

		if m.Errors[i] != nil {
			if err := m.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetPaymentRefundResponse) validateRefund(formats strfmt.Registry) error {

	if swag.IsZero(m.Refund) { // not required
		return nil
	}

	if m.Refund != nil {
		if err := m.Refund.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("refund")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetPaymentRefundResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetPaymentRefundResponse) UnmarshalBinary(b []byte) error {
	var res GetPaymentRefundResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
