// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InventoryTransfer Represents the transfer of a quantity of product inventory at a
// particular time from one location to another.
//
// swagger:model InventoryTransfer
type InventoryTransfer struct {

	// The Square generated ID of the
	// `CatalogObject` being tracked.
	CatalogObjectID string `json:"catalog_object_id,omitempty"`

	// The `CatalogObjectType` of the
	// `CatalogObject` being tracked.Tracking is only
	// supported for the `ITEM_VARIATION` type.
	CatalogObjectType string `json:"catalog_object_type,omitempty"`

	// A read-only timestamp in RFC 3339 format that indicates when Square
	// received the transfer request.
	CreatedAt string `json:"created_at,omitempty"`

	// The Square ID of the `Employee` responsible for the
	// inventory transfer.
	EmployeeID string `json:"employee_id,omitempty"`

	// The Square ID of the `Location` where the related
	// quantity of items were tracked before the transfer.
	FromLocationID string `json:"from_location_id,omitempty"`

	// A unique ID generated by Square for the
	// `InventoryTransfer`.
	ID string `json:"id,omitempty"`

	// A client-generated timestamp in RFC 3339 format that indicates when
	// the transfer took place. For write actions, the `occurred_at` timestamp
	// cannot be older than 24 hours or in the future relative to the time of the
	// request.
	OccurredAt string `json:"occurred_at,omitempty"`

	// The number of items affected by the transfer as a decimal string.
	// Can support up to 5 digits after the decimal point.
	//
	// _Important_: The Point of Sale app and Dashboard do not currently support
	// decimal quantities. If a Point of Sale app or Dashboard attempts to read a
	// decimal quantity on inventory counts or adjustments, the quantity will be rounded
	// down to the nearest integer. For example, `2.5` will become `2`, and `-2.5`
	// will become `-3`.
	// Read [Decimal Quantities (BETA)](https://developer.squareup.com/docs/docs/inventory-api/what-it-does#decimal-quantities-beta) for more information.
	Quantity string `json:"quantity,omitempty"`

	// An optional ID provided by the application to tie the
	// `InventoryTransfer` to an external system.
	ReferenceID string `json:"reference_id,omitempty"`

	// Read-only information about the application that initiated the
	// inventory transfer.
	Source *SourceApplication `json:"source,omitempty"`

	// The `InventoryState` for the quantity of
	// items being transfered.
	// See [InventoryState](#type-inventorystate) for possible values
	State string `json:"state,omitempty"`

	// The Square ID of the `Location` where the related
	// quantity of items were tracked after the transfer.
	ToLocationID string `json:"to_location_id,omitempty"`
}

// Validate validates this inventory transfer
func (m *InventoryTransfer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InventoryTransfer) validateSource(formats strfmt.Registry) error {

	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InventoryTransfer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InventoryTransfer) UnmarshalBinary(b []byte) error {
	var res InventoryTransfer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
