// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListWorkweekConfigsRequest A request for a set of `WorkweekConfig` objects
// Example: {"request_params":"?limit=1\u0026cursor=s4R0Z6ecFTzTC4jz8sUDBQTudX3KE313OT9fCt3VUgsXM4sMgED"}
//
// swagger:model ListWorkweekConfigsRequest
type ListWorkweekConfigsRequest struct {

	// Pointer to the next page of Workweek Config results to fetch.
	Cursor string `json:"cursor,omitempty"`

	// Maximum number of Workweek Configs to return per page.
	Limit int64 `json:"limit,omitempty"`
}

// Validate validates this list workweek configs request
func (m *ListWorkweekConfigsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list workweek configs request based on context it is used
func (m *ListWorkweekConfigsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListWorkweekConfigsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListWorkweekConfigsRequest) UnmarshalBinary(b []byte) error {
	var res ListWorkweekConfigsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
