// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListEmployeeWagesResponse The response to a request for a set of `EmployeeWage` objects. Contains
// a set of `EmployeeWage`.
//
// swagger:model ListEmployeeWagesResponse
type ListEmployeeWagesResponse struct {

	// Value supplied in the subsequent request to fetch the next next page
	// of Employee Wage results.
	Cursor string `json:"cursor,omitempty"`

	// A page of Employee Wage results.
	EmployeeWages []*EmployeeWage `json:"employee_wages"`

	// Any errors that occurred during the request.
	Errors []*Error `json:"errors"`
}

// Validate validates this list employee wages response
func (m *ListEmployeeWagesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmployeeWages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListEmployeeWagesResponse) validateEmployeeWages(formats strfmt.Registry) error {

	if swag.IsZero(m.EmployeeWages) { // not required
		return nil
	}

	for i := 0; i < len(m.EmployeeWages); i++ {
		if swag.IsZero(m.EmployeeWages[i]) { // not required
			continue
		}

		if m.EmployeeWages[i] != nil {
			if err := m.EmployeeWages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("employee_wages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *ListEmployeeWagesResponse) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.Errors) { // not required
		return nil
	}

	for i := 0; i < len(m.Errors); i++ {
		if swag.IsZero(m.Errors[i]) { // not required
			continue
		}

		if m.Errors[i] != nil {
			if err := m.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListEmployeeWagesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListEmployeeWagesResponse) UnmarshalBinary(b []byte) error {
	var res ListEmployeeWagesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
