// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListCatalogRequest list catalog request
// Example: {"request_params":"?types=category,tax"}
//
// swagger:model ListCatalogRequest
type ListCatalogRequest struct {

	// The specific version of the catalog objects to be included in the response.
	// This allows you to retrieve historical
	// versions of objects. The specified version value is matched against
	// the `CatalogObject`s' `version` attribute.
	CatalogVersion int64 `json:"catalog_version,omitempty"`

	// The pagination cursor returned in the previous response. Leave unset for an initial request.
	// See [Pagination](https://developer.squareup.com/docs/basics/api101/pagination) for more information.
	Cursor string `json:"cursor,omitempty"`

	// An optional case-insensitive, comma-separated list of object types to retrieve, for example
	// `ITEM,ITEM_VARIATION,CATEGORY,IMAGE`.
	//
	// The legal values are taken from the CatalogObjectType enum:
	// `ITEM`, `ITEM_VARIATION`, `CATEGORY`, `DISCOUNT`, `TAX`,
	// `MODIFIER`, `MODIFIER_LIST`, or `IMAGE`.
	Types string `json:"types,omitempty"`
}

// Validate validates this list catalog request
func (m *ListCatalogRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list catalog request based on context it is used
func (m *ListCatalogRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListCatalogRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListCatalogRequest) UnmarshalBinary(b []byte) error {
	var res ListCatalogRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
