// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OrderCreatedObject order created object
//
// swagger:model OrderCreatedObject
type OrderCreatedObject struct {

	// Information about the created order.
	OrderCreated *OrderCreated `json:"order_created,omitempty"`
}

// Validate validates this order created object
func (m *OrderCreatedObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOrderCreated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCreatedObject) validateOrderCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.OrderCreated) { // not required
		return nil
	}

	if m.OrderCreated != nil {
		if err := m.OrderCreated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("order_created")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this order created object based on the context it is used
func (m *OrderCreatedObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOrderCreated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCreatedObject) contextValidateOrderCreated(ctx context.Context, formats strfmt.Registry) error {

	if m.OrderCreated != nil {
		if err := m.OrderCreated.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("order_created")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderCreatedObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCreatedObject) UnmarshalBinary(b []byte) error {
	var res OrderCreatedObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
