// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaymentOptions payment options
//
// swagger:model PaymentOptions
type PaymentOptions struct {

	// Indicates whether the Payment objects created from this `TerminalCheckout` will automatically be
	// COMPLETED or left in an APPROVED state for later modification.
	Autocomplete bool `json:"autocomplete,omitempty"`
}

// Validate validates this payment options
func (m *PaymentOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentOptions) UnmarshalBinary(b []byte) error {
	var res PaymentOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
