// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RenewTokenRequest renew token request
// Example: {"request_body":{"access_token":"ACCESS_TOKEN"}}
//
// swagger:model RenewTokenRequest
type RenewTokenRequest struct {

	// The token you want to renew.
	AccessToken string `json:"access_token,omitempty"`
}

// Validate validates this renew token request
func (m *RenewTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this renew token request based on context it is used
func (m *RenewTokenRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RenewTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RenewTokenRequest) UnmarshalBinary(b []byte) error {
	var res RenewTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
