// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RetrieveLoyaltyRewardRequest A request to retrieve a loyalty reward.
// Example: {"request_params":"?reward_id=9f18ac21-233a-31c3-be77-b45840f5a810"}
//
// swagger:model RetrieveLoyaltyRewardRequest
type RetrieveLoyaltyRewardRequest interface{}
