// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RetrieveWageSettingRequest Represents a retrieve request for the wage setting of a team member
//
// swagger:model RetrieveWageSettingRequest
type RetrieveWageSettingRequest interface{}
