// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RevokeTokenRequest revoke token request
//
// swagger:model RevokeTokenRequest
type RevokeTokenRequest struct {

	// The access token of the merchant whose token you want to revoke.
	// Do not provide a value for merchant_id if you provide this parameter.
	AccessToken string `json:"access_token,omitempty"`

	// The Square issued ID for your application, available from the
	// [application dashboard](https://connect.squareup.com/apps).
	ClientID string `json:"client_id,omitempty"`

	// The ID of the merchant whose token you want to revoke.
	// Do not provide a value for access_token if you provide this parameter.
	MerchantID string `json:"merchant_id,omitempty"`

	// If `true`, terminate the given single access token, but do not
	// terminate the entire authorization.
	// Default: `false`
	RevokeOnlyAccessToken bool `json:"revoke_only_access_token,omitempty"`
}

// Validate validates this revoke token request
func (m *RevokeTokenRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RevokeTokenRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RevokeTokenRequest) UnmarshalBinary(b []byte) error {
	var res RevokeTokenRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
