// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShiftSort Sets the sort order of search results.
//
// swagger:model ShiftSort
type ShiftSort struct {

	// The field to sort on.
	// See [ShiftSortField](#type-shiftsortfield) for possible values
	Field string `json:"field,omitempty"`

	// The order in which results are returned. Defaults to DESC.
	// See [SortOrder](#type-sortorder) for possible values
	Order string `json:"order,omitempty"`
}

// Validate validates this shift sort
func (m *ShiftSort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this shift sort based on context it is used
func (m *ShiftSort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShiftSort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShiftSort) UnmarshalBinary(b []byte) error {
	var res ShiftSort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
