// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StandardUnitDescriptionGroup Group of standard measurement units.
//
// swagger:model StandardUnitDescriptionGroup
type StandardUnitDescriptionGroup struct {

	// IETF language tag.
	LanguageCode string `json:"language_code,omitempty"`

	// List of standard (non-custom) measurement units in this description group.
	StandardUnitDescriptions []*StandardUnitDescription `json:"standard_unit_descriptions"`
}

// Validate validates this standard unit description group
func (m *StandardUnitDescriptionGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStandardUnitDescriptions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StandardUnitDescriptionGroup) validateStandardUnitDescriptions(formats strfmt.Registry) error {

	if swag.IsZero(m.StandardUnitDescriptions) { // not required
		return nil
	}

	for i := 0; i < len(m.StandardUnitDescriptions); i++ {
		if swag.IsZero(m.StandardUnitDescriptions[i]) { // not required
			continue
		}

		if m.StandardUnitDescriptions[i] != nil {
			if err := m.StandardUnitDescriptions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("standard_unit_descriptions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *StandardUnitDescriptionGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StandardUnitDescriptionGroup) UnmarshalBinary(b []byte) error {
	var res StandardUnitDescriptionGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
