// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerminalRefundQuerySort terminal refund query sort
//
// swagger:model TerminalRefundQuerySort
type TerminalRefundQuerySort struct {

	// The order in which results are listed.
	// - `ASC` - oldest to newest
	// - `DESC` - newest to oldest (default).
	SortOrder string `json:"sort_order,omitempty"`
}

// Validate validates this terminal refund query sort
func (m *TerminalRefundQuerySort) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this terminal refund query sort based on context it is used
func (m *TerminalRefundQuerySort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TerminalRefundQuerySort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerminalRefundQuerySort) UnmarshalBinary(b []byte) error {
	var res TerminalRefundQuerySort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
