// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpsertCatalogObjectResponse upsert catalog object response
//
// swagger:model UpsertCatalogObjectResponse
type UpsertCatalogObjectResponse struct {

	// The successfully created or updated CatalogObject.
	CatalogObject *CatalogObject `json:"catalog_object,omitempty"`

	// Information on any errors encountered.
	Errors []*Error `json:"errors"`

	// The mapping between client and server IDs for this upsert.
	IDMappings []*CatalogIDMapping `json:"id_mappings"`
}

// Validate validates this upsert catalog object response
func (m *UpsertCatalogObjectResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCatalogObject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDMappings(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpsertCatalogObjectResponse) validateCatalogObject(formats strfmt.Registry) error {

	if swag.IsZero(m.CatalogObject) { // not required
		return nil
	}

	if m.CatalogObject != nil {
		if err := m.CatalogObject.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("catalog_object")
			}
			return err
		}
	}

	return nil
}

func (m *UpsertCatalogObjectResponse) validateErrors(formats strfmt.Registry) error {

	if swag.IsZero(m.Errors) { // not required
		return nil
	}

	for i := 0; i < len(m.Errors); i++ {
		if swag.IsZero(m.Errors[i]) { // not required
			continue
		}

		if m.Errors[i] != nil {
			if err := m.Errors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("errors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpsertCatalogObjectResponse) validateIDMappings(formats strfmt.Registry) error {

	if swag.IsZero(m.IDMappings) { // not required
		return nil
	}

	for i := 0; i < len(m.IDMappings); i++ {
		if swag.IsZero(m.IDMappings[i]) { // not required
			continue
		}

		if m.IDMappings[i] != nil {
			if err := m.IDMappings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("id_mappings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpsertCatalogObjectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpsertCatalogObjectResponse) UnmarshalBinary(b []byte) error {
	var res UpsertCatalogObjectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
