// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1BankAccount V1BankAccount
//
// swagger:model V1BankAccount
type V1BankAccount struct {

	// The last few digits of the bank account number.
	AccountNumberSuffix string `json:"account_number_suffix,omitempty"`

	// The name of the bank that manages the account.
	BankName string `json:"bank_name,omitempty"`

	// The currency code of the currency associated with the bank account, in ISO 4217 format. For example, the currency code for US dollars is USD.
	CurrencyCode string `json:"currency_code,omitempty"`

	// The bank account's Square-issued ID.
	ID string `json:"id,omitempty"`

	// The Square-issued ID of the merchant associated with the bank account.
	MerchantID string `json:"merchant_id,omitempty"`

	// The name associated with the bank account.
	Name string `json:"name,omitempty"`

	// The bank account's routing number.
	RoutingNumber string `json:"routing_number,omitempty"`

	// The bank account's type (for example, savings or checking).
	// See [V1BankAccountType](#type-v1bankaccounttype) for possible values
	Type string `json:"type,omitempty"`
}

// Validate validates this v1 bank account
func (m *V1BankAccount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1BankAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1BankAccount) UnmarshalBinary(b []byte) error {
	var res V1BankAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
