// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Variation V1Variation
//
// swagger:model V1Variation
type V1Variation struct {

	// The item variation's unique ID.
	ID string `json:"id,omitempty"`

	// If the inventory quantity for the variation is less than or equal to this value and inventory_alert_type is LOW_QUANTITY, the variation displays an alert in the merchant dashboard.
	InventoryAlertThreshold int64 `json:"inventory_alert_threshold,omitempty"`

	// Indicates whether the item variation displays an alert when its inventory quantity is less than or equal to its inventory_alert_threshold.
	// See [V1VariationInventoryAlertType](#type-v1variationinventoryalerttype) for possible values
	InventoryAlertType string `json:"inventory_alert_type,omitempty"`

	// The ID of the variation's associated item.
	ItemID string `json:"item_id,omitempty"`

	// The item variation's name.
	Name string `json:"name,omitempty"`

	// Indicates the variation's list position when displayed in Square Point of Sale and the merchant dashboard. If more than one variation for the same item has the same ordinal value, those variations are displayed in alphabetical order
	Ordinal int64 `json:"ordinal,omitempty"`

	// The item variation's price, if any.
	PriceMoney *V1Money `json:"price_money,omitempty"`

	// Indicates whether the item variation's price is fixed or determined at the time of sale.
	// See [V1VariationPricingType](#type-v1variationpricingtype) for possible values
	PricingType string `json:"pricing_type,omitempty"`

	// The item variation's SKU, if any.
	Sku string `json:"sku,omitempty"`

	// If true, inventory tracking is active for the variation.
	TrackInventory bool `json:"track_inventory,omitempty"`

	// Arbitrary metadata associated with the variation. Cannot exceed 255 characters.
	UserData string `json:"user_data,omitempty"`

	// The ID of the CatalogObject in the Connect v2 API. Objects that are shared across multiple locations share the same v2 ID.
	V2ID string `json:"v2_id,omitempty"`
}

// Validate validates this v1 variation
func (m *V1Variation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePriceMoney(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Variation) validatePriceMoney(formats strfmt.Registry) error {

	if swag.IsZero(m.PriceMoney) { // not required
		return nil
	}

	if m.PriceMoney != nil {
		if err := m.PriceMoney.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("price_money")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Variation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Variation) UnmarshalBinary(b []byte) error {
	var res V1Variation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
