// Code generated by go-swagger; DO NOT EDIT.

package labor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/jefflinse/square-connect/models"
)

// GetEmployeeWageReader is a Reader for the GetEmployeeWage structure.
type GetEmployeeWageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEmployeeWageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEmployeeWageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEmployeeWageOK creates a GetEmployeeWageOK with default headers values
func NewGetEmployeeWageOK() *GetEmployeeWageOK {
	return &GetEmployeeWageOK{}
}

/* GetEmployeeWageOK describes a response with status code 200, with default header values.

Success
*/
type GetEmployeeWageOK struct {
	Payload *models.GetEmployeeWageResponse
}

func (o *GetEmployeeWageOK) Error() string {
	return fmt.Sprintf("[GET /v2/labor/employee-wages/{id}][%d] getEmployeeWageOK  %+v", 200, o.Payload)
}
func (o *GetEmployeeWageOK) GetPayload() *models.GetEmployeeWageResponse {
	return o.Payload
}

func (o *GetEmployeeWageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetEmployeeWageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
